print('Введите все стадии развития человека по возрастанию (от самых древних)')
a1 = input()
a2 = input()
a3 = input()
a4 = input()
a5 = input()
b1 = input()
b2 = input()
b3 = input()
b4 = input()
b5 = input()
print(a1, a2, a3, a4, a5, b1, b2, b3, b4, b5, sep='=>')
